%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\User\Dropbox\2 - Spider Silk Research\Papers\Papers
%    - (2015) 1st Belgian Spider Silk\Uncertainties for simulation.xlsx
%    Worksheet: forUpload
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/03/20 15:05:07

%% Import the data
[~, ~, raw] = xlsread('Uncertainties for simulation.xlsx','forUpload','A2:AJ2');

%[~, ~, raw] = xlsread('C:\Users\Troy\Dropbox\2 - Spider Silk Research\Papers\Papers - (2015) 1st Belgian Spider Silk\Uncertainties for simulation.xlsx','forUpload','A2:AH2');


%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
sZ = data(:,1);
bWL = data(:,2);
bI = data(:,3);
bT = data(:,4);
bt = data(:,5);
bNoise = data(:,6);
bSN = data(:,7);
bPIb = data(:,8);
bPWLb = data(:,9);
bFWHMb = data(:,10);
bDb = data(:,11);
bPIm = data(:,12);
bPWLm = data(:,13);
bFWHMm = data(:,14);
bDm = data(:,15);
bZ = data(:,16);
bTfit = data(:,17);
bFreq = data(:,18);
sZ = data(:,19);
sWL = data(:,20);
sI = data(:,21);
sT = data(:,22);
st = data(:,23);
sNoise = data(:,24);
sSN = data(:,25);
sPIb = data(:,26);
sPWLb = data(:,27);
sFWHMb = data(:,28);
sDb = data(:,29);
sPIm = data(:,30);
sPWLm = data(:,31);
sFWHMm = data(:,32);
sDm = data(:,33);
sZ = data(:,34);
sTfit = data(:,35);
sFreq = data(:,36);

%%
uZ = 2*sqrt(bZ^2 + sZ^2);
uWL = 2*sqrt(bWL^2 + sWL^2);
uI = 2*sqrt(bI^2 + sI^2);
uT = 2*sqrt(bT^2 + sT^2);
ut = 2*sqrt(bt^2 + st^2);
uNoise = 2*sqrt(bNoise^2 + sNoise^2);
uSN = 2*sqrt(bSN^2 + sSN^2);
uPIb = 2*sqrt(bPIb^2 + sPIb^2);
uPWLb = 2*sqrt(bPWLb^2 + sPWLb^2);
uFWHMb = 2*sqrt(bFWHMb^2 + sFWHMb^2);
uDb = 2*sqrt(bDb^2 + sDb^2);
uPIm = 2*sqrt(bPIm^2 + sPIm^2);
uPWLm = 2*sqrt(bPWLm^2 + sPWLm^2);
uFWHMm = 2*sqrt(bFWHMm^2 + sFWHMm^2);
uDm = 2*sqrt(bDm^2 + sDm^2);
uZ = 2*sqrt(bZ^2 + sZ^2);
uTfit = 2*sqrt(bTfit^2 + sTfit^2);
uFreq = 2*sqrt(bFreq^2 + sFreq^2);

uVectorNums = [uZ,uWL,uI,uT,ut,uNoise,uSN,uPIb,uPWLb,uFWHMb,uDb,uPIm,uPWLm,uFWHMm,uDm,uZ,uTfit,uFreq];
uVectorNames = {'uZ','uWL','uI','uT','ut','uNoise','uSN','uPIb','uPWLb','uFWHMb','uDb','uPIm','uPWLm','uFWHMm','uDm','uZ','uTfit','uFreq'};


%% Clear temporary variables
clearvars data raw;